# Clearly, from 1 to 100, there are ten numbers with 3 as the unit's
# digit- 3, 13, 23, 33, 43, 53, 63, 73, 83, 93; and ten numbers with 3 as the ten's digit -
# 30, 31, 32, 33, 34, 35, 36, 37, 38, 39.

# So, required number = 10 + 10 = 20.



# count=0
# i=0
# while i<100:
#     if i%10==3:
#         count+=1
#     i=i+1
# print(count)
# count1=0
# j=0
# while j<100:
#     if j//10==3:
#         count1+=1
#         # print(j,end=" ") #30 31 32 33 34 35 36 37 38 39
#     j=j+1
# print(count1)
# print(count+count1)
